### ISSUE TITLE
"types" directory missing?

### ISSUE THREAD

**Issue by phoneticallySAARTHaK** [Keillion/MutablePromise#1]
Hey, I just forked the project, installed node modules, and ran the build command, but the types folder seems to be missing in the dist folder:

```
[sarthak@eos MutablePromise]$ ls dist/
index.d.ts      index.esm.js      index.js      index.min.js      index.min.mjs      index.mjs
index.d.ts.map  index.esm.min.js  index.js.map  index.min.js.map  index.min.mjs.map  index.mjs.map
```

**Comment by Keillion** [comment]
I have updated all dependencies to the latest ([commit](https://github.com/Keillion/MutablePromise/commit/70ea0b81140f1aa5fb3d7f714b6f40d06ded5410)). Now it should works.
